apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.ingress.metadata.name }}"
  labels:
    name: "{{ .Values.ingress.metadata.label.name }}"
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .serviceNameFrontend }}
              servicePort: {{ .servicePort }}
    {{- end }}